---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/python-311:latest

dependencies:
  collections:
    - name: kubernetes.core
    - name: google.cloud

options:
  package_manager_path: /usr/bin/microdnf
