---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/python39:latest
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0
  galaxy: requirements.yml

options:
  package_manager_path: /usr/bin/microdnf
