---
version: 3

images:
  base_image:
    # Needs login if pulling from Red Hat registry, or update this 
    # to point to your Hub's local container registry instead.
    name: 192.168.3.215/ee-minimal-rhel9:latest

dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
    
  # Use Ansible Core 2.14
  ansible_core:
    package_pip: ansible-core
    
  # Runner
  ansible_runner:
    package_pip: ansible-runner
    
  # Collections to be installed via Private Automation Hub (configured via GH Actions env)
  galaxy:
    collections:
      - infra.aap_configuration
      - infra.aap_configuration_extended
      - name: ansible.controller
        version: ">=4.5.0"
      - name: ansible.platform
      - name: ansible.eda

  system: bindep.txt

additional_build_steps:
  prepend_galaxy:
    - ENV ANSIBLE_GALAXY_SERVER_LIST=my_hub,gald
    - ENV ANSIBLE_GALAXY_SERVER_MY_HUB_URL=https://192.168.3.215/api/galaxy/content/rh-certified/
    - ENV ANSIBLE_GALAXY_SERVER_MY_HUB_VALIDATE_CERTS=false
    - ARG ANSIBLE_GALAXY_SERVER_MY_HUB_TOKEN
    - ENV ANSIBLE_GALAXY_SERVER_MY_HUB_TOKEN=$ANSIBLE_GALAXY_SERVER_MY_HUB_TOKEN
    - ENV ANSIBLE_GALAXY_SERVER_GALD_URL=https://192.168.3.215/api/galaxy/content/validated/
    - ENV ANSIBLE_GALAXY_SERVER_GALD_VALIDATE_CERTS=false
    - ARG ANSIBLE_GALAXY_SERVER_GALD_TOKEN
    - ENV ANSIBLE_GALAXY_SERVER_GALD_TOKEN=$ANSIBLE_GALAXY_SERVER_GALD_TOKEN
  append_final:
    - ENV ANSIBLE_GALAXY_SERVER_LIST=my_hub,gald
    - ENV ANSIBLE_GALAXY_SERVER_MY_HUB_URL=https://192.168.3.215/api/galaxy/content/rh-certified/
    - ENV ANSIBLE_GALAXY_SERVER_MY_HUB_VALIDATE_CERTS=false
    - ENV ANSIBLE_GALAXY_SERVER_GALD_URL=https://192.168.3.215/api/galaxy/content/validated/
    - ENV ANSIBLE_GALAXY_SERVER_GALD_VALIDATE_CERTS=false

options:
  package_manager_path: /usr/bin/microdnf
