---
version: 3

images:
  base_image:
    # Needs login if pulling from Red Hat registry, or update this 
    # to point to your Hub's local container registry instead.
    name: 192.168.3.215/ee-minimal-rhel9:latest

dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
    
  # Use Ansible Core 2.14
  ansible_core:
    package_pip: ansible-core
    
  # Runner
  ansible_runner:
    package_pip: ansible-runner
    
  # Collections to be installed via Private Automation Hub (configured via GH Actions env)
  galaxy:
    collections:
      - infra.aap_configuration
      - infra.aap_configuration_extended
      - name: ansible.controller
        version: ">=4.6.0"
      - name: ansible.platform
      - name: ansible.eda

  system: bindep.txt

additional_build_steps:
  prepend_galaxy:
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
    - RUN ansible-galaxy collection install --no-deps --pre --server "${ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL}" --api-key "${ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN}" --ignore-certs --collections-path "/usr/share/ansible/collections" infra.aap_configuration infra.aap_configuration_extended ansible.controller ansible.platform ansible.eda

options:
  package_manager_path: /usr/bin/microdnf
