[libdefaults]
    default_realm = YOURDOMAIN.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false

[realms]
    YOURDOMAIN.LOCAL = {
        kdc = dc1.yourdomain.local
        kdc = dc2.yourdomain.local
        admin_server = dc1.yourdomain.local
    }

[domain_realm]
    .yourdomain.local = YOURDOMAIN.LOCAL
    yourdomain.local = YOURDOMAIN.LOCAL